spring:
  jackson:
    default-property-inclusion: non_null

logging:
  pattern:
    console: "%clr(%-5level) %white([%thread]) %cyan(%logger{36}): %msg%n"
#  level:
    #   Hibernate loggers
#    org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor: trace
#    org.hibernate.event.internal.AbstractFlushingEventListener: trace
#    org.hibernate.internal.util.EntityPrinter: trace
#    org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl: trace
#    org.hibernate.internal.SessionImpl: trace
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.hibernate.orm.jdbc.extract: trace
#    org.hibernate.hql.ast.AST: info
#    org.hibernate.tool.hbm2ddl: warn
#    org.hibernate.hql: debug
#    org.hibernate.cache: info
#    org.hibernate.jdbc: debug
#    org.hibernate.stat: debug