spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:library}
    username: ${POSTGRES_USER:usr}
    password: ${POSTGRES_PASSWORD:pwd}
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      # Property to enable DB initialization by using data.sql and schema.sql files
      mode: always

logging:
  pattern:
    console: "%clr(%-5level) %white([%thread]) %cyan(%logger{36}): %msg%n"
  level:
    edu.sandbox.javadatabasetools.mybatis.mapper: debug