logging:
  level:
    # Spring loggers
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.core.StatementCreatorUtils: trace
    org.springframework.transaction.interceptor: trace