spring:
  datasource:
    url: jdbc:log4jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:library}
    username: ${POSTGRES_USER:usr}
    password: ${POSTGRES_PASSWORD:pwd}
    driver-class-name: net.sf.log4jdbc.DriverSpy
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null

logging:
  pattern:
    console: "%clr(%-5level) %white([%thread]) %cyan(%logger{36}): %msg%n"
  level:
    # Spring JDBC loggers
#    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.support.JdbcTransactionManager: debug

    # Log4JDBC loggers
    jdbc.audit: error
    jdbc.resultset: error
    jdbc.sqltiming: error
    jdbc.connection: error
    log4jdbc.debug: trace
    jdbc.sqlonly: info